### ISSUE TITLE
Make a TODO list :)

### ISSUE THREAD

**Issue by AarjavP** [connorwood93/TodoList#1]
- [ ] Scope the project
- [ ] Breakdown the work to achieve the scope
- [ ] Prioritize and assign the broken down components
